/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zendesk.endwork;


import org.zendesk.client.v2.Zendesk;

public class App {


    public static void main(String[] args) {
        Zendesk zd = new Zendesk.Builder("https://{{your domain}}.zendesk.com")
                .setUsername("...")
                .setToken("...")
                .build();

    }
}
